import { AuraProfile } from "../types";

export const demoProfiles: AuraProfile[] = [
  {
    id: "you",
    displayName: "Malek",
    bio: "Calm but passionate, loves building things and connecting with people who feel safe and honest.",
    avatarUrl: "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=400",
    vibeTags: ["calm", "curious", "romantic"],
    ageRange: "26",
    country: "Hungary",
    introversionLevel: 5,
    goals: ["Connect with others", "Find someone genuine"],
    vibeWords: ["calm", "curious", "romantic"],
    topicsLike: ["deep conversations", "tech", "travel", "philosophy"],
    topicsAvoid: ["superficial chat", "negativity"],
    socialSpeed: "normal",
    hardBoundaries: ["disrespect", "ghosting", "dishonesty"],
    greenFlags: ["authenticity", "kindness", "humor"],
    redFlags: ["judgmental", "game-playing"],
    summary: "Calm but passionate, loves building things and connecting with people who feel safe and honest."
  },
  {
    id: "lina",
    displayName: "Lina",
    bio: "Soft, shy, and playful once she trusts you. Needs emotional safety more than anything.",
    avatarUrl: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400",
    vibeTags: ["soft", "playful", "introverted"],
    ageRange: "24",
    country: "Turkey",
    introversionLevel: 8,
    goals: ["Find connection", "Build trust slowly"],
    vibeWords: ["soft", "playful", "introverted"],
    topicsLike: ["anime", "late-night talks", "quiet cafés", "art"],
    topicsAvoid: ["loud parties", "pressure", "small talk"],
    socialSpeed: "slow",
    hardBoundaries: ["loud parties", "pressure to open up fast"],
    greenFlags: ["patience", "gentleness", "creative"],
    redFlags: ["pushiness", "superficiality"],
    summary: "Soft, shy, and playful once she trusts you. Needs emotional safety more than anything."
  },
  {
    id: "alex",
    displayName: "Alex",
    bio: "Witty introvert who loves gaming, indie music, and deep late-night conversations.",
    avatarUrl: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400",
    vibeTags: ["witty", "creative", "thoughtful"],
    ageRange: "25",
    country: "Canada",
    introversionLevel: 7,
    goals: ["Find like-minded friend", "Build trust"],
    vibeWords: ["witty", "creative", "thoughtful"],
    topicsLike: ["indie games", "indie music", "memes", "sci-fi"],
    topicsAvoid: ["mainstream trends", "fakeness"],
    socialSpeed: "slow",
    hardBoundaries: ["toxicity", "judgment"],
    greenFlags: ["genuine", "funny", "nerdy"],
    redFlags: ["shallow", "mean-spirited"],
    summary: "Witty introvert who loves gaming, indie music, and deep late-night conversations about everything."
  },
  {
    id: "maya",
    displayName: "Maya",
    bio: "Nature lover, yoga enthusiast, seeks meaningful connections over coffee or hiking.",
    avatarUrl: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400",
    vibeTags: ["peaceful", "grounded", "warm"],
    ageRange: "27",
    country: "Spain",
    introversionLevel: 4,
    goals: ["Find genuine friends", "Grow together"],
    vibeWords: ["peaceful", "grounded", "warm"],
    topicsLike: ["hiking", "yoga", "wellness", "travel"],
    topicsAvoid: ["negativity", "drama", "superficial"],
    socialSpeed: "normal",
    hardBoundaries: ["unkindness", "waste of time"],
    greenFlags: ["authentic", "peaceful", "curious"],
    redFlags: ["drama", "negativity"],
    summary: "Nature lover, yoga enthusiast, seeks meaningful connections over coffee or hiking adventures."
  },
  {
    id: "jordan",
    displayName: "Jordan",
    bio: "Bookworm with a passion for writing, coffee, and people-watching at cozy spots.",
    avatarUrl: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400",
    vibeTags: ["thoughtful", "artistic", "introspective"],
    ageRange: "23",
    country: "UK",
    introversionLevel: 8,
    goals: ["Find understanding friend", "Creative collaboration"],
    vibeWords: ["thoughtful", "artistic", "introspective"],
    topicsLike: ["books", "writing", "poetry", "coffee culture"],
    topicsAvoid: ["loud clubs", "sports small talk"],
    socialSpeed: "slow",
    hardBoundaries: ["interrupting", "judgment of interests"],
    greenFlags: ["literate", "thoughtful", "curious"],
    redFlags: ["dismissive", "shallow"],
    summary: "Bookworm with a passion for writing, coffee, and people-watching at cozy spots around the city."
  }
];
